name: Release

on:
  push:
    tags:
      - "v*"

env:
  BUILD_TYPE: Release

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install OpenSSL
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install openssl.light

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Upload binary
      if: ${{ matrix.os != 'windows-latest' }}
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          **/DEternal_loadMods
          /usr/lib/x86_64-linux-gnu/libcrypto.so
          /usr/lib/x86_64-linux-gnu/libssl.so

    - name: Upload exe
      if: ${{ matrix.os == 'windows-latest' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: "**/DEternal_loadMods.exe"
        tag: ${{ github.ref }}
