name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  BUILD_TYPE: Debug

jobs:
  windows-test:
    runs-on: windows-2019

    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install OpenSSL
      run: choco install openssl

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -T clangcl

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}

  linux-test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        export CC=gcc-10
        export CXX=g++-10
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
