name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  BUILD_TYPE: Debug

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install OpenSSL
      if: ${{ matrix.os == 'windows-latest' }}
      run: choco install openssl

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - name: Upload artifact
      if: ${{ matrix.os != 'windows-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: |
          ${{ github.workspace }}/build/DEternal_loadMods
          /usr/lib/x86_64-linux-gnu/libcrypto.so
          /usr/lib/x86_64-linux-gnu/libssl.so

    - name: Upload artifact
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: ${{ github.workspace }}\build\Debug\DEternal_loadMods.exe
